# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/RLMS
spring.datasource.username=postgres
spring.datasource.password=Mohan5936
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Formatting the SQL in console (makes it easier to read)
spring.jpa.properties.hibernate.format_sql=true