spring.datasource.url=jdbc:mysql://root:tqGspdCEUUliNWGARaKXmbhBaTsEdtIH@centerbeam.proxy.rlwy.net:23750/railway
spring.datasource.username=root
spring.datasource.password=tqGspdCEUUliNWGARaKXmbhBaTsEdtIH

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true